# Lab | Pandas

Objective: practice how to use the pandas library in Python for data analysis and manipulation.

In this lab, we will be working with the customer data from an insurance company, which can be found in the CSV file located at the following link: https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file1.csv

The data includes information such as customer ID, state, gender, education, income, and other variables that can be used to perform various analyses.

Throughout the lab, we will be using the pandas library in Python to manipulate and analyze the data. Pandas is a powerful library that provides various data manipulation and analysis tools, including the ability to load and manipulate data from a variety of sources, including CSV files.

### Data Description

- Customer - Customer ID

- ST - State where customers live

- Gender - Gender of the customer

- Education - Background education of customers 

- Customer Lifetime Value - Customer lifetime value(CLV) is the total revenue the client will derive from their entire relationship with a customer. In other words, is the predicted or calculated value of a customer over their entire duration as a policyholder with the insurance company. It is an estimation of the net profit that the insurance company expects to generate from a customer throughout their relationship with the company. Customer Lifetime Value takes into account factors such as the duration of the customer's policy, premium payments, claim history, renewal likelihood, and potential additional services or products the customer may purchase. It helps insurers assess the long-term profitability and value associated with retaining a particular customer.

- Income - Customers income

- Monthly Premium Auto - Amount of money the customer pays on a monthly basis as a premium for their auto insurance coverage. It represents the recurring cost that the insured person must pay to maintain their insurance policy and receive coverage for potential damages, accidents, or other covered events related to their vehicle.

- Number of Open Complaints - Number of complaints the customer opened

- Policy Type - There are three type of policies in car insurance (Corporate Auto, Personal Auto, and Special Auto)

- Vehicle Class - Type of vehicle classes that customers have Two-Door Car, Four-Door Car SUV, Luxury SUV, Sports Car, and Luxury Car

- Total Claim Amount - the sum of all claims made by the customer. It represents the total monetary value of all approved claims for incidents such as accidents, theft, vandalism, or other covered events.

External Resources: https://towardsdatascience.com/filtering-data-frames-in-pandas-b570b1f834b9

## Challenge 1: Understanding the data

In this challenge, you will use pandas to explore a given dataset. Your task is to gain a deep understanding of the data by analyzing its characteristics, dimensions, and statistical properties.

- Identify the dimensions of the dataset by determining the number of rows and columns it contains.
- Determine the data types of each column and evaluate whether they are appropriate for the nature of the variable. You should also provide suggestions for fixing any incorrect data types.
- Identify the number of unique values for each column and determine which columns appear to be categorical. You should also describe the unique values of each categorical column and the range of values for numerical columns, and give your insights.
- Compute summary statistics such as mean, median, mode, standard deviation, and quartiles to understand the central tendency and distribution of the data for numerical columns. You should also provide your conclusions based on these summary statistics.
- Compute summary statistics for categorical columns and providing your conclusions based on these statistics.

In [130]:
# data clean up
import pandas as pd
import numpy as np
import statistics as stats

data = pd.read_csv('customer.csv')
data = data.dropna(subset=['Customer'])

data = data.drop_duplicates()

for col in data.columns:
    data['ST'] = data['ST'].replace('AZ', 'Arizona')
    data['ST'] = data['ST'].replace('WA', 'Washington')
    data['ST'] =  data['ST'].replace('Cali', 'California')
    data['GENDER'] =  data['GENDER'].replace('Femal', 'F')
    data['GENDER'] =  data['GENDER'].replace('female', 'F')
    data['GENDER'] =  data['GENDER'].replace('Male', 'M')
    
    print(col, data[col].unique())
        
print(data.head)

display(data.dtypes)

Customer ['RB50392' 'QZ44356' 'AI49188' ... 'GS98873' 'CW49887' 'MY31220']
ST ['Washington' 'Arizona' 'Nevada' 'California' 'Oregon']
GENDER [nan 'F' 'M']
Education ['Master' 'Bachelor' 'High School or Below' 'College' 'Bachelors' 'Doctor']
Customer Lifetime Value [nan '697953.59%' '1288743.17%' ... '2031499.76%' '323912.47%'
 '899704.02%']
Income [    0. 48767. 36357. 62902. 55350. 14072. 28812. 77026. 99845. 83689.
 24599. 25049. 28855. 51148. 66140. 57749. 61040. 17870. 97541. 29723.
 86584. 75690. 23158. 65999. 37260. 68987. 42305. 65706. 53243. 50071.
 60021. 43244. 46896. 10105. 23218. 24804. 33190. 36014. 67163. 16701.
 46623. 64749. 16969. 11621. 17622. 11489. 66525. 33663. 22547. 61486.
 29879. 93011. 65186. 26840. 75644. 38984. 71811. 20961. 41275. 61321.
 51066. 34378. 43072. 25222. 77552. 23091. 48269. 32720. 20396. 21513.
 80744. 52822. 69738. 17780. 18107. 57740. 32627. 65795. 60475. 41837.
 32303. 40531. 79898. 56398. 71600. 27804. 45506. 99428. 20993. 37839.
 92711. 74665. 61108. 46833. 88768. 28262. 33555. 42780. 58850. 21880.
 25251. 25317. 24188. 41611. 28406. 69833. 80536. 88891. 97732. 61222.
 50335. 82210. 64495. 28859. 77330. 33060. 42557. 26372. 17514. 89270.
 29757. 51814. 24028. 28142. 52705. 54040. 22492. 21876. 70699. 27501.
 15897. 25141. 28358. 62530. 90972. 63110. 29549. 39411. 21709. 67890.
 84311. 99316. 54507. 64586. 61709. 94656. 61085. 89284. 31686. 56855.
 53703. 27679. 23904. 65351. 64459. 32961. 71416. 68964. 78108. 10621.
 84910. 77493. 81097. 96610. 30110. 22081. 98473. 97431. 93870. 50366.
 34498. 16552. 26787. 43860. 21474. 18174. 60920. 41520. 72208. 53863.
 66446. 64997. 64460. 46618. 49988. 16269. 72006. 44320. 19782. 63933.
 28224. 21073. 63243. 94827. 39161. 37534. 80210. 21708. 94731. 32375.
 16531. 32006. 81676. 71038. 20832. 52405. 26583. 25486. 24065. 70435.
 39679. 53565. 37574. 48259. 78532. 96163. 72672. 99002. 79494. 35704.
 26049. 70125. 52369. 41770. 31911. 70051. 19683. 30916. 84302. 60145.
 63774. 25134. 37057. 58577. 85857. 70602. 33816. 89642. 60068. 50044.
 36650. 50653. 68931. 39266. 40864. 39035. 34923. 24506. 52220. 53554.
 34476. 68205. 53690. 74454. 29664. 72450. 47272. 21585. 23827. 69906.
 73196. 72217. 46131. 54514. 96668. 78879. 29735. 23082. 53984. 52135.
 17576. 29486. 58557. 25632. 18768. 47945. 58778. 15192. 51859. 23422.
 21604. 79298. 76731. 38460. 48534. 30817. 48412. 68798. 23712. 72196.
 68197. 75248. 89879. 46998. 57099. 33897. 59207. 40171. 80192. 74422.
 34226. 65989. 30686. 20090. 77094. 97413. 79189. 18577. 62777. 17483.
 84394. 41440. 98132. 88220. 58327. 25950. 65726. 84768. 36234. 58842.
 25629. 77311. 95697. 22254. 65974. 92079. 67752. 25398. 33321. 38923.
 20325. 13129. 49080. 42536. 29926. 21450. 33345. 15752. 40169. 55411.
 12459. 64620. 83140. 54422. 68309. 56621. 38977. 83235. 32390. 66538.
 23285. 76358. 21104. 12964. 33288. 56168. 23105. 36218. 52275. 49665.
 32471. 62773. 76694. 55687. 36633. 77060. 92600. 64801. 45257. 26854.
 85840. 26463. 30689. 29590. 25965. 17269. 90330. 18558. 46384. 42303.
 71731. 26173. 24445. 72302. 27208. 30855. 99960. 55873. 18052. 28937.
 12829. 92163. 17588. 41546. 70340. 34549. 93459. 86148. 27048. 73259.
 35482. 29462. 67801. 16042. 28056. 16495. 41163. 33799. 90125. 87747.
 35695. 90985. 66839. 79090. 24825. 26806. 56835. 46135. 22862. 95854.
 44897. 64455. 53265. 50450. 54780. 67798. 21442. 27615. 50200. 73570.
 70412. 36631. 35895. 93018. 70014. 48875. 67969. 68665. 26802. 45345.
 89689. 32051. 81139. 63834. 37548. 72421. 83102. 28432. 83707. 63259.
 63860. 43836. 86132. 28519. 39102. 97298. 41986. 17291. 37256. 96306.
 14290. 37038. 90760. 77048. 54480. 16244. 22436. 71592. 28728. 57449.
 83318. 75217. 55308. 36068. 48804. 55790. 70258. 47274. 44705. 70446.
 64348. 88997. 10312. 96263. 28919. 41869. 32808. 79780. 91025. 33043.
 69442. 47234. 86863. 25805. 43676. 59855. 35296. 36576. 28513. 85448.
 23791. 20597. 56940. 93210. 48992. 53736. 25378. 37722. 69379. 33806.
 94041. 74965. 34095. 96045. 86355. 27824. 42995. 21235. 74585. 41833.
 23908. 61953. 73760. 23333. 20440. 27658. 50943. 19003. 46703. 21733.
 20811. 11904. 43490. 57340. 49088. 47761. 61281. 25290. 24239. 82664.
 83210. 38736. 55437. 68041. 29066. 54337. 67616. 41082. 50631. 19592.
 55761. 41449. 62007. 21921. 42621. 63786. 82877. 10475. 21952. 49721.
 88340. 24589. 73769. 66670. 88854. 31266. 67267. 79270. 36692. 44624.
 19614. 83846. 51159. 83772. 88440. 25666. 52926. 40001. 18024. 23220.
 64125. 58042. 90034. 27972. 50989. 11885. 89451. 78904. 70247. 32653.
 93595. 90279. 53310. 22234. 91375. 22250. 51179. 38667. 79487. 67763.
 71943. 53526. 35005. 24721. 48587. 76310. 73205. 51056. 58414. 23940.
 44216. 29305. 53882. 91757. 33906. 68158. 42165. 68074. 84978. 71135.
 64642. 46754. 70410. 66957. 24213. 99790. 79751. 86122. 82297. 89057.
 43259. 25064. 25816. 41662. 96170. 46072. 37931. 35127. 45473. 93087.
 22398. 92983. 27689. 69654. 18608. 73168. 70930. 62262. 91474. 61469.
 16618. 48081. 67632. 34115. 23051. 23748. 40589. 50809. 66676. 52339.
 14973. 31546. 20836. 88592. 66943. 81872. 22404. 21342. 34621. 62396.
 97212. 49648. 97984. 26308. 63528. 20225. 87620. 34990. 99934. 60804.
 94648. 24516. 61063. 15169. 55390. 27592. 61846. 83297. 55897. 21297.
 87560. 89398. 36843. 34946. 75680. 49532. 10269. 49714. 77517. 81082.
 72540. 61546. 44818. 79797. 92717. 63568. 73935. 18846. 38893. 84824.
 20068. 97245. 51808. 71391. 23496. 55561. 23986. 22974. 61844. 27760.
 52266. 23599. 36088. 70534. 27398. 85296. 31063. 52367. 58651. 84831.
 70263. 45354. 28334. 38772. 41479. 23909. 48328. 86689. 24204. 25943.
 62375. 70200. 79027. 62935. 26893. 47406. 27572. 32802. 62739. 90844.
 44685. 42589. 93383. 79583. 89129. 94389. 84106. 76717. 51978. 47325.
 86721. 24910. 43817. 59537. 54193. 86946. 12160. 33701. 85702. 69417.
 38644. 63209. 16061. 54230.]
Monthly Premium Auto [ 1000.    94.   108.   106.    68.    69.    67.   101.    71.    93.
   110.    70.    64.    72.    74.    79.    73.    61.   111.    80.
    63.   237.    65.   130.    62.   117.    91.    90.    66.    99.
   103. 35354.   172.    92.   104.   113.   124.   105.   100.   112.
    97.    95.   102.    96.   186.    77.    76.   119.    87.   109.
   107.    88.    85.  6464.   133.    86.    78.    89.   192.   118.
   140.   127.   126.    82.   115.   217.   114.   138.    81.   255.
   150.   123.   116.   190.    98.   159.    84.    83.   152.   136.
   245.   135.  1005.   225.   132.   153.   121.   139.   154.   161.
   156.   171.   244.   183.   176.   230.   129.   177.   181.   196.
   131.   276.   253.   137.   180.   203.   147.   165.   198.   125.
   193.   128.   271.   142. 10202.   206.   182.   189.   160.   295.
   210.   134. 35353.   239.   188.   256.   173.   285.   148.   141.
   197.   199.]
Number of Open Complaints ['1/0/00' '1/2/00' '1/1/00' '1/3/00' '1/5/00' '1/4/00']
Policy Type ['Personal Auto' 'Corporate Auto' 'Special Auto']
Vehicle Class ['Four-Door Car' 'Two-Door Car' 'SUV' 'Luxury SUV' 'Sports Car'
 'Luxury Car']
Total Claim Amount [2.70493400e+00 1.13146493e+03 5.66472247e+02 5.29881344e+02
 1.72693230e+01 1.59383042e+02 3.21600000e+02 3.63029680e+02
 5.11200000e+02 4.25527834e+02 4.82400000e+02 5.28000000e+02
 4.72029737e+02 3.07139132e+02 4.29202710e+01 4.54245098e+02
 6.47442031e+02 3.08981664e+02 4.84800000e+02 3.55200000e+02
 2.03828760e+01 5.54376763e+02 4.39200000e+02 3.89185006e+02
 7.99200000e+02 2.09851050e+01 5.32800000e+02 3.84000000e+02
 3.22294043e+02 6.15927769e+02 3.08150890e+02 2.38201580e+01
 1.54376810e+01 2.04475147e+02 5.61600000e+02 4.36800000e+02
 6.48000000e+02 1.57397849e+02 4.84318536e+02 1.89189350e+01
 8.82871945e+02 4.94400000e+02 3.17073170e+01 5.17753000e-01
 5.79165954e+02 4.47793440e+02 5.29624084e+02 3.13023175e+02
 5.93830288e+02 5.08800000e+02 1.73956072e+02 3.31928030e+01
 8.31625979e+02 3.02565190e+02 7.04768111e+02 5.18400000e+02
 3.12000000e+02 5.04000000e+02 8.63327324e+02 1.04331355e+02
 6.76391482e+02 3.50400000e+02 5.37600000e+02 4.65258644e+02
 4.56000000e+02 5.00254235e+02 2.81451042e+02 5.43450500e+00
 3.07200000e+02 9.82399613e+02 4.67803638e+02 2.90341600e+01
 4.11223030e+01 4.27631210e+02 2.58076850e+01 7.87993313e+02
 4.89600000e+02 3.02400000e+02 4.75623251e+02 4.52150590e+01
 4.60800000e+02 2.82151207e+02 3.64800000e+02 6.79827592e+02
 4.60414520e+01 1.18790370e+01 3.50529033e+02 8.63394700e+02
 4.92127532e+02 1.32588288e+02 2.97600000e+02 2.69905129e+02
 3.80036697e+02 5.13600000e+02 4.25266308e+02 4.90110990e+01
 9.36000000e+02 1.42062768e+02 4.51525210e+01 3.05673570e+01
 2.71606799e+02 4.08000000e+02 4.61581170e+01 7.84800000e+02
 3.16800000e+02 4.80468690e+01 6.38400000e+02 4.65633954e+02
 3.68400146e+02 2.36902001e+02 4.94511170e+01 6.41096630e+01
 3.26400000e+02 9.21600000e+02 1.01896450e+02 5.42400000e+02
 1.43747794e+02 4.24077159e+02 5.04221810e+01 5.23200000e+02
 1.13801497e+02 1.92875720e+02 8.28662719e+02 9.75107098e+02
 5.37987080e+01 5.05283550e+01 2.89912200e+02 3.92604371e+02
 7.21242206e+02 4.56523850e+02 1.08799543e+03 5.19619150e+01
 2.51992083e+02 3.45600000e+02 9.92576080e+01 5.67315780e+01
 5.75623240e+01 6.04800000e+02 8.31272900e+00 3.16599228e+02
 5.63007240e+01 3.93600000e+02 7.01708239e+02 1.28705563e+02
 6.79368378e+02 5.99871260e+01 5.66400000e+02 6.16542620e+01
 5.54400000e+02 4.65414770e+02 4.96800000e+02 2.92800000e+02
 2.56813837e+02 5.42319401e+02 3.03148399e+02 2.54380630e+01
 8.40244130e+01 6.16937710e+01 2.32926145e+02 6.81797210e+01
 7.10433775e+02 5.52000000e+02 1.12265890e+03 4.08374746e+02
 7.92000000e+02 7.54358929e+02 7.02990032e+02 2.06837111e+02
 2.75395894e+02 4.59738128e+02 3.36000000e+02 4.30994107e+02
 1.83600000e+03 6.76324760e+01 8.44481918e+02 7.22486994e+02
 5.90400000e+02 4.81027516e+02 1.12442773e+03 6.69682001e+02
 1.28409317e+03 2.40259479e+02 9.12000000e+02 5.56800000e+02
 1.15086827e+02 4.70400000e+02 3.83167471e+02 3.07963291e+02
 5.20364752e+02 4.66436375e+02 4.51670309e+02 3.31200000e+02
 4.28734656e+02 3.98400000e+02 3.69600000e+02 8.31752839e+02
 1.56124914e+02 3.73428187e+02 3.95934815e+02 2.31201886e+02
 2.89904105e+02 7.29600000e+02 1.05765111e+02 6.39464548e+02
 3.83442328e+02 9.90859430e+01 5.66935022e+02 4.12800000e+02
 3.88800000e+02 2.34541344e+03 7.73470977e+02 4.24883448e+02
 3.64240307e+02 3.54729129e+02 2.83995953e+02 4.03200000e+02
 2.05431760e+01 3.85115437e+02 1.40165035e+02 1.02879769e+02
 5.68682890e+01 4.63158502e+02 2.05444066e+02 7.41600000e+02
 5.63719670e+01 8.13600000e+02 7.95864079e+02 6.14400000e+02
 7.24386810e+01 6.78815460e+01 4.02636829e+02 6.41388616e+02
 3.42481173e+02 3.40800000e+02 4.12101933e+02 7.37005730e+01
 3.74400000e+02 7.22024742e+02 2.59361117e+02 3.96295614e+02
 3.58281562e+02 6.53388564e+02 1.21032372e+02 9.28133960e+01
 1.59636956e+02 4.76156957e+02 7.27200000e+02 4.20783450e+01
 2.00116060e+02 6.76944023e+02 7.66092950e+01 8.30623064e+02
 5.80473259e+02 6.00366830e+01 4.75310100e+01 3.03872752e+02
 1.00620067e+02 4.81339891e+02 1.10160000e+03 8.63200220e+01
 6.67200000e+02 5.66033300e+01 2.62865172e+02 3.09577946e+02
 3.65364581e+02 7.05600000e+02 9.51528000e+00 2.44564334e+02
 6.39105556e+02 4.53600000e+02 5.54522969e+02 4.02449823e+02
 3.27020539e+02 5.39530000e+00 1.31401291e+02 9.93829430e+01
 8.56800000e+02 7.39200000e+02 8.42183630e+01 6.45468770e+01
 4.41600000e+02 3.79106230e+01 2.02860399e+02 8.58098170e+01
 9.11466610e+01 2.86234931e+02 1.15920000e+03 4.66570791e+02
 1.25240623e+03 4.21484456e+02 4.30505942e+02 3.98502948e+02
 7.64676300e+00 5.55105260e+01 3.51270869e+02 8.06400000e+02
 6.47454583e+02 1.28438230e+02 3.02033971e+02 4.80000000e+02
 1.00316063e+03 3.79200000e+02 2.44362072e+02 2.01455005e+02
 9.15509800e+01 9.18346680e+01 7.07430832e+02 9.29152510e+01
 3.76126419e+02 1.52184244e+02 1.76819414e+02 1.04454624e+02
 9.41718054e+02 4.68000000e+02 9.40303080e+01 6.78598810e+01
 5.39843003e+02 9.51931570e+01 9.53385050e+01 6.26400000e+02
 4.94395024e+02 1.15545086e+02 1.99389810e+01 7.99926741e+02
 8.78400000e+02 4.44470676e+02 2.68819985e+02 1.01288069e+02
 1.31760000e+03 6.91412378e+02 8.04811859e+02 1.09086434e+03
 5.05870350e+01 1.51528482e+02 3.47075948e+02 2.71697529e+02
 8.49600000e+02 1.10484661e+02 1.13534474e+02 5.95200000e+02
 1.13609508e+02 1.33706349e+03 1.14273025e+02 1.25194389e+02
 2.35220971e+02 3.95341110e+02 1.14798771e+02 7.72798511e+02
 6.33600000e+02 1.68517149e+02 8.45654042e+02 1.15728852e+02
 6.68293970e+02 7.00901632e+02 5.25600000e+02 2.52990000e+01
 3.75330097e+02 4.18233667e+02 3.98240791e+02 9.38513425e+02
 3.38619869e+02 3.39344531e+02 3.02818833e+02 6.19165344e+02
 2.59561195e+02 1.79161843e+02 6.62400000e+02 7.55018520e+01
 3.06983596e+02 8.40268480e+01 1.39489926e+02 6.07445900e+02
 6.31124372e+02 6.28023494e+02 4.26655599e+02 9.14179230e+01
 3.17844812e+02 1.18446235e+02 8.64615820e+01 1.18454974e+02
 3.62774545e+02 2.21856184e+02 9.80169081e+02 6.14675906e+02
 1.45252168e+02 3.74240783e+02 6.19200000e+02 8.06692570e+01
 1.32480000e+03 4.68566133e+02 8.42437850e+02 4.75200000e+02
 1.17193117e+03 2.68471802e+02 1.38722385e+02 4.67248020e+02
 4.67503236e+02 1.21440000e+03 1.92085299e+02 6.19973889e+02
 1.00278255e+03 2.51774574e+02 8.66208321e+02 1.21092095e+03
 5.99648466e+02 2.02772444e+03 7.28520470e+01 4.49819671e+02
 2.59060862e+02 2.99356083e+02 6.99167900e+02 1.17959654e+02
 5.45240341e+02 3.28231432e+02 6.65686420e+01 1.38240000e+03
 1.21306839e+02 6.09600000e+02 1.25933005e+02 6.55413330e+02
 6.73342650e+02 2.38104910e+01 4.51200000e+02 2.31922173e+02
 7.72800000e+02 6.64980242e+02 1.28645946e+02 4.64920390e+01
 4.32000000e+02 7.80851490e+01 5.64466556e+02 2.89040734e+02
 1.55938593e+02 3.26549425e+02 6.53656680e+02 1.03935601e+02
 8.09532341e+02 5.80725310e+02 1.33735395e+02 2.38005074e+02
 1.57767442e+03 1.35892444e+02 1.35261250e+02 5.71200000e+02
 6.37063458e+02 7.59360960e+01 1.36291083e+02 6.75309040e+01
 3.12921256e+02 1.66937747e+02 1.35382194e+02 1.77429540e+01
 1.83836700e+00 1.97776009e+02 6.12102262e+02 1.19303615e+03
 6.00000000e+02 1.36829537e+02 9.26400000e+02 3.92636400e+02
 2.15226476e+02 1.60598662e+02 3.71803029e+02 4.43670399e+02
 6.12300581e+02 2.90391526e+02 3.16795337e+02 4.05527937e+02
 2.08598246e+02 1.38130879e+02 3.01437365e+02 4.56473115e+02
 1.52338562e+02 4.91755368e+02 4.85174390e+01 4.30375049e+02
 2.46489123e+02 1.28969729e+02 1.85355353e+02 1.30080000e+03
 9.07130500e+00 1.33475315e+02 1.41199465e+02 6.23223617e+02
 4.27200000e+02 1.41725051e+02 2.11336937e+02 1.47080303e+02
 8.62762957e+02 1.13367765e+02 9.43200000e+02 1.17672722e+02
 2.25145949e+02 1.82432565e+02 1.48173152e+02 1.55570802e+02
 2.12391975e+02 1.74041566e+02 4.86278557e+02 1.92470900e+00
 2.62122050e+02 5.41695658e+02 3.27682669e+02 1.26557030e+03
 6.30431970e+01 1.56313630e+01 3.75866091e+02 4.52616872e+02
 1.13450122e+02 1.60345100e+01 6.15272280e+02 6.15256301e+02
 5.12662450e+02 7.45239350e+01 4.26072946e+02 1.69287785e+02
 4.19464143e+02 1.58077504e+02 6.69600000e+02 3.95729716e+02
 1.59756733e+02 5.85575520e+01 8.58297100e+00 2.85418473e+02
 4.10508316e+02 2.44231350e+02 2.18598065e+02 6.43826716e+02
 4.97047297e+02 1.02240000e+03 6.57600000e+02 2.30245772e+02
 5.62275100e+00 1.60075260e+02 3.46513050e+01 6.78100487e+02
 1.74588413e+02 1.59391681e+02 6.98400000e+02 2.32711071e+02
 1.63046956e+02 7.98656050e+01 3.82085897e+02 4.83483190e+01
 1.33425609e+02 5.61414794e+02 4.45287788e+02 1.65570243e+02
 4.07996840e+02 8.44229478e+02 3.40306584e+02 1.06647493e+02
 6.26116259e+02 7.84657810e+02 5.47200000e+02 8.62777200e+01
 6.35165720e+01 1.20015609e+02 1.25413790e+03 4.17600000e+02
 7.98002689e+02 8.20416840e+01 2.28190880e+01 4.22400000e+02
 6.39971388e+02 5.11497882e+02 2.39540223e+02 5.18180364e+02
 7.15252366e+02 4.02070719e+02 9.48140320e+01 9.72000000e+02
 7.38830440e+01 5.74024018e+02 6.32715382e+02 4.23862600e+00
 4.22480870e+01 2.71451510e+01 2.70002766e+02 4.94946438e+02
 1.42567008e+02 2.51334247e+02 3.69818708e+02 1.61419528e+02
 2.55999709e+02 6.17695640e+01 1.31040000e+03 2.50001424e+02
 1.41799422e+02 4.97970160e+01 3.72175592e+02 5.42143850e+02
 1.36080000e+03 7.68000000e+02 7.26329340e+01 7.20601429e+02
 5.76000000e+02 4.81025786e+02 4.66176731e+02 1.59266473e+02
 4.12831670e+01 5.03808329e+02 8.59599411e+02 3.05653785e+02
 2.78902846e+02 1.41600000e+03 1.39963594e+02 7.34400000e+02
 3.72998650e+01 9.58165160e+01 1.00800000e+03 4.46400000e+02
 7.22053620e+01 4.01592109e+02 2.53183568e+02 6.43200000e+02
 7.99673766e+02 2.79878670e+01 1.66772960e+02 2.70563995e+02
 1.78006524e+02 4.04265696e+02 5.13818403e+02 1.31828507e+02
 6.28800000e+02 1.78986788e+02 3.92235698e+02 8.73600000e+02
 3.82107000e-01 1.87363583e+02 3.50853987e+02 2.17973168e+02
 2.59340640e+01 1.88938397e+02 1.53205591e+02 2.89323968e+03
 6.29532731e+02 3.61284757e+02 1.18598830e+03 4.25800112e+02
 1.90434460e+02 1.93505325e+02 2.40877740e+01 2.19288706e+02
 8.81360959e+02 2.69516270e+01 4.66122541e+02 6.07095655e+02
 2.90381707e+02 5.58099357e+02 8.28000000e+02 5.40514115e+02
 1.00049832e+02 5.98619630e+01 1.93570320e+02 1.99797270e+02
 5.30847530e+01 2.56438030e+02 2.11136067e+02 7.43508930e+01
 6.21464468e+02 3.60055890e+02 6.59548130e+01 4.07450118e+02
 1.22880000e+03 2.40636930e+01 3.11329282e+02 4.26891350e+01
 4.60323855e+02 2.13225001e+02 3.00607591e+02 2.62504882e+02
 2.63365432e+02 2.56268091e+02 2.15818200e+02 1.35360000e+03
 4.99200000e+02 4.55079520e+01 6.91200000e+02 8.24099220e+01
 3.57642982e+02 4.20356980e+02 1.36787725e+02 2.20186677e+02
 1.70798204e+02 2.66165535e+02 9.89217820e+01 2.81295903e+02
 6.31743039e+02 2.92095210e+01 1.36883999e+02 3.17556010e+01
 2.24275820e+02 8.30400000e+02 4.80159011e+02 3.90792553e+02
 7.20711950e+01 4.19652520e+01 1.02700003e+03 3.19820747e+02
 4.11011162e+02 4.11058500e+00 3.51149904e+02 2.84000172e+02
 4.96474767e+02 9.25137143e+02 1.31640970e+01 2.27872071e+02
 4.63335061e+02 1.80667969e+02 3.02764283e+02 1.41922839e+02
 3.49783046e+02 5.40655380e+01 3.42515136e+02 1.02717726e+03
 2.75989978e+02 4.72599683e+02 1.33693172e+03 7.34594600e+00
 5.40141566e+02 3.83363758e+02 5.37765151e+02 3.21873474e+02
 1.95756830e+01 1.08138715e+02 7.07303416e+02 1.06733313e+03
 8.07947292e+02 6.18630955e+02 4.04272806e+02 7.10400000e+02
 7.07977614e+02 2.32242326e+02 6.82260010e+01 2.87149807e+02
 3.91636628e+02 2.39328571e+02 2.32674417e+02 3.36509610e+02
 2.44212286e+02 3.28870868e+02 8.50637080e+01 1.41840000e+03
 3.34408717e+02 4.20964150e+01 3.00528579e+02 1.44782152e+02
 6.45982160e+01 3.47857619e+02 2.45447622e+02 9.55200000e+02
 7.20752945e+02 3.40656963e+02 5.46524896e+02 4.89411833e+02
 1.71325856e+02 2.49085887e+02 3.08748690e+01 3.61455219e+02
 2.07320041e+02]
<bound method NDFrame.head of      Customer          ST GENDER             Education  \
0     RB50392  Washington    NaN                Master
1     QZ44356     Arizona      F              Bachelor
2     AI49188      Nevada      F              Bachelor
3     WW63253  California      M              Bachelor
4     GA49547  Washington      M  High School or Below
...       ...         ...    ...                   ...
1066  TM65736      Oregon      M                Master
1067  VJ51327  California      F  High School or Below
1068  GS98873     Arizona      F              Bachelor
1069  CW49887  California      F                Master
1070  MY31220  California      F               College

     Customer Lifetime Value   Income  Monthly Premium Auto  \
0                        NaN      0.0                1000.0
1                 697953.59%      0.0                  94.0
2                1288743.17%  48767.0                 108.0
3                 764586.18%      0.0                 106.0
4                 536307.65%  36357.0                  68.0
...                      ...      ...                   ...
1066              305955.03%  38644.0                  78.0
1067             2031499.76%  63209.0                 102.0
1068              323912.47%  16061.0                  88.0

Customer                      object
ST                            object
GENDER                        object
Education                     object
Customer Lifetime Value       object
Income                       float64
Monthly Premium Auto         float64
Number of Open Complaints     object
Policy Type                   object
Vehicle Class                 object
Total Claim Amount           float64
dtype: object

In [165]:
# Your code here

data = pd.read_csv('customer.csv')
display(data.head(30))
display(data.dtypes)
# Number of open compalaints should be integers (maybe divided into open, closed and total claims) - Total Claim Accounts should be round in cents - Customer Lifetime Value should in float
for col in data.columns:
    if data[col].nunique() < 20:
        print(col, data[col].unique())
        
min_value_income = data['Income'].min()
max_value_income = data['Income'].max()
range_income = max_value_income - min_value_income

print(range_income)

min_value_mpa = data['Monthly Premium Auto'].min()
max_value_mpa = data['Monthly Premium Auto'].max()
range_mpa = max_value_mpa - min_value_mpa

print(range_mpa)

min_value_tca = data['Total Claim Amount'].min()
max_value_tca = data['Total Claim Amount'].max()
range_tca = max_value_tca - min_value_tca

print(range_tca)

# CLV and income have a huge range, while TCA is not that big

print( "mode tca", stats.mode(data['Total Claim Amount']), "mode income",
stats.mode(data['Income']), "mode mpa",
stats.mode(data['Monthly Premium Auto']))

print("mean tca", stats.mean(data['Total Claim Amount']), "mean income",
stats.mean(data['Income']), "mean mpa",
stats.mean(data['Monthly Premium Auto']))

print("median tcs", stats.median(data['Total Claim Amount']), "median income",
stats.median(data['Income']), "median MPA",
stats.median(data['Monthly Premium Auto']))
      
print("st dev tca", data['Total Claim Amount'].std(), "st dev income",
data['Income'].std(), "st dev mpa",
data['Monthly Premium Auto'].std())

# I do not know how to get the info about the quartils becuase we do not have (or cannot find this info in the table)

# TCA has an unexpected high standard deviation compared to its mean. While CLF has a smaller range but a lower standard deviation

,Customer,ST,GENDER,Education,Customer Lifetime Value,Income,Monthly Premium Auto,Number of Open Complaints,Policy Type,Vehicle Class,Total Claim Amount
0,RB50392,Washington,NaN,Master,NaN,0.0,1000.0,1/0/00,Personal Auto,Four-Door Car,2.704934
1,QZ44356,Arizona,F,Bachelor,697953.59%,0.0,94.0,1/0/00,Personal Auto,Four-Door Car,1131.464935
2,AI49188,Nevada,F,Bachelor,1288743.17%,48767.0,108.0,1/0/00,Personal Auto,Two-Door Car,566.472247
3,WW63253,California,M,Bachelor,764586.18%,0.0,106.0,1/0/00,Corporate Auto,SUV,529.881344
4,GA49547,Washington,M,High School or Below,536307.65%,36357.0,68.0,1/0/00,Personal Auto,Four-Door Car,17.269323
5,OC83172,Oregon,F,Bachelor,825629.78%,62902.0,69.0,1/0/00,Personal Auto,Two-Door Car,159.383042
6,XZ87318,Oregon,F,College,538089.86%,55350.0,67.0,1/0/00,Corporate Auto,Four-Door Car,321.600000
7,CF85061,Arizona,M,Master,721610.03%,0.0,101.0,1/0/00,Corporate Auto,Four-Door Car,363.029680
8,DY87989,Oregon,M,Bachelor,2412750.40%,14072.0,71.0,1/0/00,Corporate Auto,Four-Door Car,511.200000
9,BQ94931,Oregon,F,College,738817.81%,28812.0,93.0,1/0/00,Special Auto,Four-Door Car,425.527834
10,SX51350,California,M,College,473899.20%,0.0,67.0,1/0/00,Personal Auto,Four-Door Car,482.400000
11,VQ65197,California,NaN,College,819719.71%,0.0,110.0,1/0/00,Personal Auto,SUV,528.000000
12,DP39365,California,NaN,Master,879879.70%,77026.0,110.0,1/2/00,Corporate Auto,Four-Door Car,472.029737
13,SJ95423,Arizona,NaN,High School or Below,881901.89%,99845.0,110.0,1/1/00,Corporate Auto,SUV,528.000000
14,IL66569,California,NaN,College,538443.17%,83689.0,70.0,1/2/00,Corporate Auto,Four-Door Car,307.139132
15,BW63560,Oregon,NaN,Bachelor,746313.94%,24599.0,64.0,1/1/00,Corporate Auto,Four-Door Car,42.920271
16,FV94802,Nevada,NaN,High School or Below,256686.78%,25049.0,67.0,1/0/00,Personal Auto,Two-Door Car,454.245098
17,OE15005,Cali,NaN,College,394524.16%,28855.0,101.0,1/0/00,Personal Auto,SUV,647.442031
18,WC83389,Oregon,NaN,College,571033.31%,51148.0,72.0,1/0/00,Personal Auto,Four-Door Car,308.981664
19,FL50705,California,NaN,High School or Below,816261.71%,66140.0,101.0,1/0/00,Corporate Auto,Four-Door Car,484.800000
20,ZK25313,Oregon,NaN,High School or Below,287205.13%,57749.0,74.0,1/0/00,Personal Auto,Two-Door Car,355.200000
21,QK46697,Washington,M,Bachelors,617710.93%,61040.0,79.0,1/1/00,Personal Auto,Two-Door Car,20.382876
22,YH23384,Arizona,NaN,Bachelor,2412750.40%,14072.0,71.0,1/0/00,Personal Auto,Four-Door Car,511.200000
23,TZ98966,Nevada,NaN,Bachelor,245019.10%,0.0,73.0,1/3/00,Corporate Auto,Four-Door Car,554.376763
24,HM55802,California,NaN,Bachelor,239210.79%,17870.0,61.0,1/0/00,Corporate Auto,Four-Door Car,439.200000
25,FS42516,Oregon,NaN,College,580206.60%,97541.0,72.0,1/0/00,Personal Auto,Four-Door Car,389.185006
26,US89481,California,NaN,Bachelor,394637.21%,0.0,111.0,1/0/00,Personal Auto,Four-Door Car,799.200000
27,HS14476,Washington,M,College,916206.32%,29723.0,80.0,1/0/00,Personal Auto,Four-Door Car,20.985105
28,GE62437,AZ,NaN,College,1290256.01%,86584.0,111.0,1/2/00,Personal Auto,Four-Door Car,532.800000
29,EJ77678,Oregon,NaN,Master,323536.05%,75690.0,80.0,1/1/00,Personal Auto,Four-Door Car,384.000000

Customer                      object
ST                            object
GENDER                        object
Education                     object
Customer Lifetime Value       object
Income                       float64
Monthly Premium Auto         float64
Number of Open Complaints     object
Policy Type                   object
Vehicle Class                 object
Total Claim Amount           float64
dtype: object

ST ['Washington' 'Arizona' 'Nevada' 'California' 'Oregon' 'Cali' 'AZ' 'WA'
 nan]
GENDER [nan 'F' 'M' 'Femal' 'Male' 'female']
Education ['Master' 'Bachelor' 'High School or Below' 'College' 'Bachelors' 'Doctor'
 nan]
Number of Open Complaints ['1/0/00' '1/2/00' '1/1/00' '1/3/00' '1/5/00' '1/4/00' nan]
Policy Type ['Personal Auto' 'Corporate Auto' 'Special Auto' nan]
Vehicle Class ['Four-Door Car' 'Two-Door Car' 'SUV' 'Luxury SUV' 'Sports Car'
 'Luxury Car' nan]
99960.0
35293.0
2892.857571
mode tca 321.6 mode income 0.0 mode mpa 65.0
mean tca nan mean income nan mean mpa nan
median tcs nan median income nan median MPA nan
st dev tca 293.0272599264041 st dev income 30469.42706040185 st dev mpa 1601.190368577621

## Challenge 2: analyzing the data

### Exercise 1

The marketing team wants to know the top 5 less common customer locations. Create a pandas Series object that contains the customer locations and their frequencies, and then retrieve the top 5 less common locations in ascending order.

In [139]:
# Your code here
location_counts = data['ST'].value_counts()

# Get the least common locations (top n least common)
n_least_common = 5  # Change this value to get a different number of least common locations
least_common_locations = location_counts.nsmallest(n_least_common)

print(least_common_locations)

Nevada         98
Washington    108
Arizona       211
Oregon        320
California    331
Name: ST, dtype: int64

### Exercise 2

Your goal is to identify customers with a high policy claim amount.

Instructions:

- Review again the statistics for total claim amount to gain an understanding of the data.
- To identify potential areas for improving customer retention and profitability, we want to focus on customers with a high policy claim amount. Consider customers with a high policy claim amount to be those in the top 25% of the total claim amount. Create a pandas DataFrame object that contains information about customers with a policy claim amount greater than the 75th percentile.
- Use DataFrame methods to calculate summary statistics about the high policy claim amount data.

*Note: When analyzing data, we often want to focus on certain groups of values to gain insights. Percentiles are a useful tool to help us define these groups. A percentile is a measure that tells us what percentage of values in a dataset are below a certain value. For example, the 75th percentile represents the value below which 75% of the data falls. Similarly, the 25th percentile represents the value below which 25% of the data falls. When we talk about the top 25%, we are referring to the values that fall above the 75th percentile, which represent the top quarter of the data. On the other hand, when we talk about the bottom 25%, we are referring to the values that fall below the 25th percentile, which represent the bottom quarter of the data. By focusing on these groups, we can identify patterns and trends that may be useful for making decisions and taking action.*

*Hint: look for a method that gives you the percentile or quantile 0.75 and 0.25 for a Pandas Series.*

*Hint 2: check `Boolean selection according to the values of a single column` in https://towardsdatascience.com/filtering-data-frames-in-pandas-b570b1f834b9*

In [147]:
data.head()
print(data['Total Claim Amount'])

1       1131.464935
2        566.472247
3        529.881344
4         17.269323
5        159.383042
           ...
1066     361.455219
1067     207.320041
1068     633.600000
1069     547.200000
1070     537.600000
Name: Total Claim Amount, Length: 1068, dtype: float64

In [164]:
# Your code here
# Calculate the 75th percentile and 25th percentile for each column
data.head()
policy_claim_75th_percentile = data['Total Claim Amount'].quantile(0.75)
print(policy_claim_75th_percentile)
filtered_df = data['Total Claim Amount'] > policy_claim_75th_percentile
print(filtered_df)
filtered_df.describe

mean_claim_amount = data['Total Claim Amount'].mean()
median_claim_amount = data['Total Claim Amount'].median()
std_claim_amount = data['Total Claim Amount'].std()
min_claim_amount = data['Total Claim Amount'].min()
max_claim_amount = data['Total Claim Amount'].max()
q1_claim_amount = data['Total Claim Amount'].quantile(0.25)
q3_claim_amount = data['Total Claim Amount'].quantile(0.75)

# Print the summary statistics
print("Summary Statistics for 'Total Claim Amount' column:")
print("Mean:", mean_claim_amount)
print("Median:", median_claim_amount)
print("Standard Deviation:", std_claim_amount)
print("Minimum:", min_claim_amount)
print("Maximum:", max_claim_amount)
print("25th Percentile (Q1):", q1_claim_amount)
print("75th Percentile (Q3):", q3_claim_amount)

532.8
1        True
2        True
3       False
4       False
5       False
        ...
1066    False
1067    False
1068     True
1069     True
1070     True
Name: Total Claim Amount, Length: 1068, dtype: bool
Summary Statistics for 'Total Claim Amount' column:
Mean: 405.8701129859551
Median: 355.2
Standard Deviation: 292.91715791808025
Minimum: 0.382107
Maximum: 2893.239678
25th Percentile (Q1): 204.07146
75th Percentile (Q3): 532.8

### Exercise 3

The sales team wants to know the total number of policies sold for each type of policy. Create a pandas Series object that contains the policy types and their total number of policies sold, and then retrieve the policy type with the highest number of policies sold.

*Hint:*
- *Using value_counts() method simplifies this analysis.*
- *Futhermore, there is a method that returns the index of the maximum value in a column or row.*

In [168]:
# Your code here
policy_counts = data['Policy Type'].value_counts()
print(policy_counts)

policy_type_with_highest_count = policy_counts.idxmax()
max_policies_sold = policy_counts.max()

policy_counts_series = pd.Series(policy_counts, name='Total Policies Sold')

print("Policy Type with the Highest Number of Policies Sold:", policy_type_with_highest_count)
print("Number of Policies Sold for the Highest Policy Type:", max_policies_sold)

Personal Auto     780
Corporate Auto    234
Special Auto       57
Name: Policy Type, dtype: int64
Personal Auto     780
Corporate Auto    234
Special Auto       57
Name: Total Policies Sold, dtype: int64
Policy Type with the Highest Number of Policies Sold: Personal Auto
Number of Policies Sold for the Highest Policy Type: 780

### Exercise 4

The sales team wants to know if customers with Personal Auto have less income than those with Corporate Auto. How does the average income compare between the two policy types?

- Use *loc* to create two dataframes: one containing only Personal Auto policies and one containing only Corporate Auto policies.
- Calculate the average income for each policy.
- Print the results.

In [172]:
# Your code here
personal_auto_df = data.loc[data['Policy Type'] == 'Personal Auto']
corporate_auto_df = data.loc[data['Policy Type'] == 'Corporate Auto']

print(personal_auto_df, corporate_auto_df)

average_income_personal_auto = personal_auto_df['Income'].mean()
average_income_corporate_auto = corporate_auto_df['Income'].mean()

print("Average Income for Personal Auto Policies:", average_income_personal_auto)
print("Average Income for Corporate Auto Policies:", average_income_corporate_auto)

     Customer          ST GENDER             Education  \
0     RB50392  Washington    NaN                Master
1     QZ44356     Arizona      F              Bachelor
2     AI49188      Nevada      F              Bachelor
4     GA49547  Washington      M  High School or Below
5     OC83172      Oregon      F              Bachelor
...       ...         ...    ...                   ...
1065  XD85577        Cali      M              Bachelor
1066  TM65736      Oregon      M                Master
1067  VJ51327        Cali      F  High School or Below
1068  GS98873     Arizona      F              Bachelor
1070  MY31220  California      F               College

     Customer Lifetime Value   Income  Monthly Premium Auto  \
0                        NaN      0.0                1000.0
1                 697953.59%      0.0                  94.0
2                1288743.17%  48767.0                 108.0
4                 536307.65%  36357.0                  68.0
5                 825629.78%  62902.0                  69.0
...                      ...      ...                   ...
1065              284226.69%  69417.0                  73.0
1066              305955.03%  38644.0                  78.0
1067             2031499.76%  63209.0                 102.0
1068              323912.47%  16061.0                  88.0
1070              899704.02%  54230.0                 112.0

     Number of Open Complaints    Policy Type  Vehicle Class  \
0                       1/0/00  Personal Auto  Four-Door Car
1                       1/0/00  Personal Auto  Four-Door Car
2                       1/0/00  Personal Auto   Two-Door Car
4                       1/0/00  Personal Auto  Four-Door Car
5                       1/0/00  Personal Auto   Two-Door Car
...                        ...            ...            ...
1065                    1/1/00  Personal Auto  Four-Door Car
1066                    1/1/00  Personal Auto  Four-Door Car
1067                    1/2/00  Personal Auto            SUV
1068                    1/0/00  Personal Auto  Four-Door Car
1070                    1/0/00  Personal Auto   Two-Door Car

      Total Claim Amount
0               2.704934
1            1131.464935
2             566.472247
4              17.269323
5             159.383042
...                  ...
1065           30.874869
1066          361.455219
1067          207.320041
1068          633.600000
1070          537.600000

[780 rows x 11 columns]      Customer          ST GENDER             Education  \
3     WW63253  California      M              Bachelor
6     XZ87318      Oregon      F               College
7     CF85061     Arizona      M                Master
8     DY87989      Oregon      M              Bachelor
12    DP39365  California    NaN                Master
...       ...         ...    ...                   ...
1045  WZ31900      Oregon      F              Bachelor
1050  BJ53923     Arizona      M  High School or Below
1052  FB23788      Oregon      M  High School or Below
1056  PI47776      Oregon      F              Bachelor
1059  YG44474      Oregon      M               College

     Customer Lifetime Value   Income  Monthly Premium Auto  \
3                 764586.18%      0.0                 106.0
6                 538089.86%  55350.0                  67.0
7                 721610.03%      0.0                 101.0
8                2412750.40%  14072.0                  71.0
12                879879.70%  77026.0                 110.0
...                      ...      ...                   ...
1045              864970.06%  94389.0                 107.0
1050              260027.21%  51978.0                  66.0
1052              882883.50%  86721.0                 111.0
1056              253070.51%  89451.0                  63.0
1059             1401472.13%  54193.0                 117.0

     Number of Open Complaints     Policy Type  Vehicle Class  \
3                       1/0/00  Corporate Auto            SUV
6                       1/0/00  Corporate Auto  Four-Door Car
7                       1/0/00  Corporate Auto  Four-Door Car
8                       1/0/00  Corporate Auto  Four-Door Car
12                      1/2/00  Corporate Auto  Four-Door Car
...                        ...             ...            ...
1045                    1/0/00  Corporate Auto            SUV
1050                    1/0/00  Corporate Auto  Four-Door Car
1052                    1/0/00  Corporate Auto            SUV
1056                    1/0/00  Corporate Auto  Four-Door Car
1059                    1/0/00  Corporate Auto            SUV

      Total Claim Amount
3             529.881344
6             321.600000
7             363.029680
8             511.200000
12            472.029737
...                  ...
1045           85.063708
1050          144.782152
1052          532.800000
1056           61.769564
1059          720.752945

[234 rows x 11 columns]
Average Income for Personal Auto Policies: 38180.69871794872
Average Income for Corporate Auto Policies: 41390.31196581197